version: '3'

services:
  frontend:
    image: frontendimgisa
    build: .\testreact  # Adjust this path to the actual location of your frontend code
    ports:
      - "3000:3000"  # Set the desired port for your frontend
    depends_on:
      - backend
    networks:
      - mynetwork
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8080"  # Use the service name 'backend' as the hostname

  backend:
    image: backendimgisa
    build: .
    ports:
      - "8080:12345"
    depends_on:
      - db
    networks:
      - mynetwork
      - networkdb
    environment:
      SERVER_PORT: 12345
      MONGO_URI: mongodb://db:27017


  db:
    image: databaseimgisa
    build: .\mongodb
    restart: always
    networks:
      - networkdb
    ports:
      - "27017:27017"


networks:
  mynetwork:
  networkdb:

